---
title: Configure Boot Configuration
description: Configures the boot configuration (BCD) for QoL
actions:
  # ------------------------------------------------------------------------------- #
  # https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set #
  # ------------------------------------------------------------------------------- #

    # Lowering dual boot choice time
  - !run: {exe: 'bcdedit', args: '/timeout 10'}

    # Use legacy boot menu
  - !run: {exe: 'bcdedit', args: '/set {bootloadersettings} bootmenupolicy legacy'}

    # Set boot manager descriptions
  - !run:
    exe: 'bcdedit'
    args: '/set description "AtlasOS 10"'
    builds: [ '<22000' ]
  - !run:
    exe: 'bcdedit'
    args: '/set description "AtlasOS 11"'
    builds: [ '>=22000' ]
